#!/bin/sh


while [ true ] ; do

sleep 10s

filename="backup-$(date +%Y%m%d%H%M).tar"

echo "backup-$(date +%Y%m%d%H%M) fitxategia sortzen"

touch /home/hackituria/Mahaigaina/backup_tmp/$filename

tar -cf /home/hackituria/Mahaigaina/backup_tmp/$filename -P work/

done

